feat(sdk): less cryptic error if paths are missing for `downloadFile` (#37)
If a user isn't using Typescript, they might accidentally provide the
src/dst parameters incorrectly (or forget them):

```js
const sandbox = await Sandbox.create();
await sandbox.writeFiles([
    { path: 'foo.txt', content: 'bar' }
]);
await sandbox.downloadFile({ path: 'foo.txt' }); // missing `dst` argument
```

And receive an ugly message like:

```
TypeError: Cannot read properties of undefined (reading 'cwd')
    at DisposableSandbox.downloadFile (/Users/robherley/dev/sandbox-test/node_modules/.pnpm/@vercel+sandbox@1.4.1/node_modules/@vercel/sandbox/dist/sandbox.js:315:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async main (file:///Users/robherley/dev/sandbox-test/index.mjs:9:1)
```

But now with this change, it's less cryptic:

```
Error: downloadFile: destination path is required
    at DisposableSandbox.downloadFile (/Users/robherley/vercel/sandbox/packages/vercel-sandbox/dist/sandbox.js:309:19)
    at main (file:///Users/robherley/dev/sandbox-test/index.mjs:8:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
```